#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel;

define('LARAVEL_START', microtime(true));

// Register Composer autoloader
if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
